# NOME DO WORKFLOW
name: TESTE FINAL - Gerador de Cobra

# GATILHOS: QUANDO A ACTION DEVE RODAR
on:
  # A CADA 12 HORAS, AUTOMATICAMENTE
  schedule:
    - cron: "0 */12 * * *"
  # E TAMBÉM PERMITE RODAR MANUALMENTE (ESSENCIAL PARA TESTAR)
  workflow_dispatch:

# TAREFAS QUE A ACTION VAI EXECUTAR
jobs:
  # NOME DA TAREFA
  build:
    # TIPO DE MÁQUINA VIRTUAL
    runs-on: ubuntu-latest
    # PERMISSÕES NECESSÁRIAS
    permissions:
      # PERMISSÃO PARA ESCREVER ARQUIVOS DE VOLTA NO REPOSITÓRIO
      contents: write
    # PASSOS DA TAREFA
    steps:
      # Passo 1: Baixa o repositório para a Action ter acesso aos arquivos.
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Passo 2: Usa a ação 'snk' APENAS para criar os arquivos da animação.
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Passo 3: Usa uma ação especialista para fazer o commit e push dos arquivos.
      - name: Commit & Push new animation
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # Mensagem do commit
          commit_message: "chore: update snake animation files"
          # Padrão dos arquivos que devem ser commitados (todos os .svg dentro da pasta dist)
          file_pattern: dist/*.svg
